### PR TITLE
Connects to #233. Connects to #235. Project overview page.

### PR DESCRIPTION
**Pull request by jimmyzhen**
### Key Changes:

* Added a new **Project Overview** page
* Updated landing page's **About MoTrPAC** section text and link to associate with the new **Project Overview** page
* Updated top navbar links to support the addition of new **Project Overview** and **Tutorials** pages
* Fixed QC Data Monitor top nav link bug in which initial click on the link does not invoke data fetching
* Fixed react-router behavior in which changing a route does not scroll the page back to top
* Added sectional collapsible UIs on the new **Project Overview** page

### CODE REVIEW

**Comment by jyu-sm** [comment]
Project Overview page looks fine to me but Tutorial link is current "under construction".

**Comment by jimmyzhen** [comment]
> Project Overview page looks fine to me but Tutorial link is current "under construction".
This is meant to be a placeholder page and "Coming soon" text will be replaced as soon as tutorial video is finalized.

**Comment by jimmyzhen** [comment]
@cteng585, thanks for reporting the issues. I've applied the fixes and please review again.

**Review by cteng585 — APPROVED** [review]
Thank you for all the fixes! Looks great now.

**Pull request merged**
