### PR TITLE
MOTR-255 Expiring Auth0 Session

### PR DESCRIPTION
**Pull request by jimmyzhen**
### Key Changes

1. Implemented additional handling to look up Auth0 expiration time and determine whether to terminate session.
2. Implemented a wrapper component for private routes that require authentication so that these routes do not need handling to validate authentication individually.
3. Simplified `Auth0` class methods.
4. Fixed bug contributing to failed unit test.
5. Updated unit test assertions due to changes of various components.
6. Upgraded some npm dependencies.

### Steps to test 5 use cases

**Use case 1:**
1. Sign into local instance of this branch.
2. Leave the browser window/tab open and stay _visible_ (if the tab is in a window with other tabs).
3. Verify that you are signed out after 24 hours.

**Use case 2:**
1. Sign into local instance of this branch.
2. Leave the browser window/tab open, then navigate to other tab(s) making the signed-in data hub tab _invisible_ (if the tab is in a window with other tabs).
3. After 24 hours, click on the signed-in data hub tab making it _visible_. Verify that you are signed out.

**Use case 3:**
1. Sign into local instance of this branch.
2. Close the browser window/tab of the signed-in data hub instance.
3. After 24 hours, open a new browser window/tab and access the data hub instance. Verify that you are signed out.

**Use case 4:**
1. Sign into local instance of this branch.
2. Immediately reload the page or the app.
3. Leave the browser window/tab open and stay _visible_ (if the tab is in a window with other tabs).
4. Verify that you are signed out after 24 hours.

**Use case 5:**
1. Sign into local instance of this branch.
2. Leave the browser window/tab open and stay _visible_ (if the tab is in a window with other tabs).
3. Open a different window and load the same local instance. Expect to be signed in automatically.
4. Then sign out of the local instance from either one of the windows. Verify that you are also signed out of the other one.

### CODE REVIEW

**Comment by cteng585** [comment]
After clearing cookies, all test cases worked for me. Additionally tested opening two separate windows/tabs to see if logging out of one logged out of the other and this worked for me as well. 

Some aberrant behavior that I noticed might be reproduced as follows:
1. Log in
2. Immediately refresh the page
3. Wait for expiration time to elapse. After expiration time elapses should still be able to interact with the page
4. Swap to another tab.

As soon as another tab is made active, the MOTRPAC page logs out. I'm not sure if this behavior is as intended.

**Comment by jimmyzhen** [comment]
@cteng585 Thank you for taking the time out to review the PR and to test the use cases.

In regards to the aberrant behavior you experienced, did you modify the expiration time value and the interval length (for checking the expiration) prior to signing into the webapp?

Furthermore, what was the purpose of refreshing the page immediately after successfully signing in?

**Comment by cteng585** [comment]
I did modify the expiration time value and interval length for checking expiration per your directions.

The reason why I refreshed the page immediately after successful sign in was because in one of your commits you stated "The 'unload' event is triggered by both window close and window refresh, and thus refreshing the page causes a session purge undesirably". I wasn't 100% sure about what all of that meant, but I did think that it was worth testing weird edge cases in the event of a page refresh since that was something you had addressed.

**Comment by jimmyzhen** [comment]
@cteng585 Thanks for the clarification and discovered an edge use case. I was able to reproduce the behavior and suspect that reloading the page causes the re-rendering without triggering the authentication again. This was actually by design so that we avoid the logging in needlessly. However, the expiration checking is dependent on the authentication callback. As a result, without authentication being invoked, the checking does not happen.

**Comment by kilodalton** [comment]
@cteng585  can you please re-review?

**Comment by jimmyzhen** [comment]
@cteng585, as before, for testing purpose, you can manually shorten the expiration time and the time interval to check the expiration time. However, the lines for those manual changes are now different.

For the expiration time, you may set it to 4-6 minutes upon successful login, such as changing `authResult.expiresIn` to `6*60` in the following line:
```
https://github.com/MoTrPAC/motrpac-frontend/blob/MOTR-255_JZ_Auth0_Session/src/Auth/Auth.js#L49
```
For the time interval, you may try setting it to every 2 minutes, such as changing `2 * 60 * 60 * 1000` to `2 * 60 * 1000` in the following line:
```
https://github.com/MoTrPAC/motrpac-frontend/blob/MOTR-255_JZ_Auth0_Session/src/Navbar/navbar.jsx#L39
```
If you wonder why I implemented the expiration handling in the `Navbar` component but not in the `App` component, my answer is that, at the current state, I prefer the `App` component to only handle routes without other application logic in it. Please let me know if you see a better alternative.

You will also notice that I didn’t replace the `auth0-js` library (`https://github.com/auth0/auth0.js`) with the new `auth0-react` SDK (`https://github.com/auth0/auth0-react`). I actually did make the attempt to switch, but there were issues that I struggled to debug and eventually reverted the implementation. Here is the reference to my struggle: `https://github.com/auth0/auth0-react/issues/82`

Lastly, I also attempted the implementation of **Redux Hooks** (`https://react-redux.js.org/api/hooks`) among the _connected_ components in the app in the hope to reduce the amount of boilerplate Redux code. The implementation turned out to affect both unit tests and **Storybook** components, and the effort to update them all may require a decent amount of time. And again, I reverted the implementation and will revisit it at a later time as a separate project and when there is more/better documentation on writing tests for **Redux Hooks**. Or maybe just switch to either **Redux Toolkit** (`https://redux-toolkit.js.org/`) or **Recoil** (`https://recoiljs.org/`) when they have well documented testing tutorials.

**Review by cteng585 — APPROVED** [review]
The previously noted situation with regards to the page not logging out after the expiration time if it was refreshed quickly appears to have been resolved. 

I did have one instance where, if I had multiple wrong login attempts, the login page would just hang (infinitely load) and not lock my account, but I wasn't able to reproduce this behavior despite multiple attempts.

**Comment by jimmyzhen** [comment]
@cteng585 Thank you for reviewing the PR again!

Because I didn't assign you as a reviewer previously, your approval of the PR didn't allow this PR to be merged. I have since added you again. Do you mind having it approved again? Sorry for the trouble.

**Review by cteng585 — APPROVED** [review]

**Review by cteng585 — APPROVED** [review]
Looks good, maybe 3rd times the charm?

**Pull request merged**
