### PR TITLE
Connects to #214. Connects to #215. Connects to #223. New version of portal with public access to PASS1B-06 data.

### PR DESCRIPTION
**Pull request by jimmyzhen**
### Key Changes:

1. Converted components from protected access to public access, such as DEA search, data file downloads, gene-centric view, graphical clustering. Except file downloads, the other 3 components only offer access to PASS1B-06 data.
2. Anonymous users and authenticated external users only have access to PASS1B-06 data via the file downloads component, while authenticated consortium users have access to both PASS1B-06 and PASS1A/1C-06 data via the file downloads component.
3. A publicly accessible component was added to list the links to a variety of publicly accessible GitHub repositories pertinent to PASS1B-06 data pipelines, QC and analysis.
4. A downloadable somalogic metadata file was added to the HERITAGE related study page.
5. "Vena Cava" was added to the tissue filter on the file downloads, DEA search, Gene-centric View components.
6. Typeahead feature was added to the Gene-centric View search, as well as the DEA search by gene/metabolite.
7. Gene-centric View supports the search and time-series plots of multiple genes.
8. DEA search component supports the search of either multiple genes or multiple metabolites.
9. Search filters are disabled if the returned search results do not include data matching the filters.
10. A collection of bundled PASS1B-06 data sets was added to file downloads page.
11. The "Update results" button was moved to be above the filter panels on the DEA search and Gene-centric View pages.
12. A link to the external, publicly accessible graphical clustering data visualization too was added.
13. Primary navigation bar has been relocated to the top from the side, for the purpose of keeping the overall page UIs consistent among authenticated and non-authenticated users.
14. For authenticated external users, they can now access the PASS1B-06 data sample summary, in addition to the limited PASS1A-06 data samples, upon their successful logins to the portal.

### CODE REVIEW

**Review by cteng585 — CHANGES_REQUESTED** [review]
Most of the changes look good. There are a few things that might need to be changed:

- The link to the HERITAGE study is broken; clicking on the link results in a 403 error
- The link to the _Nature Metabolism_ paper links to the homepage of Nature Metabolism, not the specified paper
- Is the Proteomics data set what is meant by "somalogic data"? If not, I don't see this data set linked anywhere
- It's odd to me that the only way to get back to the landing site is by pressing the "reset" button for the search bar

**Comment by jimmyzhen** [comment]
@cteng585 The first 3 bullet points you reported have been addressed. Please try again and let me know.

The last bullet point is odd indeed. Would you mind listing the steps to reproduce it? Thank you.

**Review by cteng585 — COMMENTED** [review]
The links to the Nature paper and proteomics data appear fixed to me. However, I'm still getting a 403 error for the HERITAGE link (shown below); is that site not available to unauthorized users?

Screenshot 2023-05-02 at 7 21 38 PM

For reproducing the last bullet point, to clarify what I mean by "landing page" I mean the page with the cards:

Screenshot 2023-05-02 at 7 15 58 PM

The behavior I experienced was searching for differential abundance of a gene or set of genes and then attempting to navigate back to the page shown above. Clicking on the MoTrPAC logo in the top left brought me back to the differential abundance page; the behavior I expected was bringing me back to the page with cards. Clicking on the search reset button brought back the card view.

Of note: this behavior is also present in the production page; I hadn't noticed it previously.

**Comment by jimmyzhen** [comment]
@cteng585 which HERITAGE link did you click on via the data hub portal that led to the 403 error?

**Comment by jimmyzhen** [comment]
@cteng585, as far as the not-so-intuitive behavior of the DEA search page, _aka_ the landing page upon logging into the portal, it will be very likely re-designed to improve the user experience, such as combining the Gene-centric View as David Amar suggested previously.

For this PR, this page is not exactly broken, and as you pointed out, it's been present in production. I will create a ticket to handle this behavior as an enhancement rather than a bug.

**Review by cteng585 — APPROVED** [review]
Thank you for the fixes Jimmy, everything looks good now.

**Pull request merged**
