### PR TITLE
MOTR-269 Release Sample Count Visualization

### PR DESCRIPTION
**Pull request by jimmyzhen**
### Key Changes

1. Replaced mocked upload/download stat UIs with UIs representing actual release sample counts in **Dashboard** component.
2. Updated **Sidebar** component with functionality to expand/collapse sidebar.
3. Added the rendering of tooltips for active sidebar items when the sidebar is collapsed.
4. Updated all pages that required authentication to support the collapsible sidebar.
5. Updated unit test assertions due to changes of various UI components.
6. Upgraded some `npm` dependencies.

### Steps to test sidebar

1. Sign into local instance of this branch.
2. Expect to see sidebar to be collapsed by default.
3. Click on the _hamburger_ menu icon at the top of the sidebar. Expect to see the sidebar being expanded.
4. Then click on the _close_ icon at the top of the sidebar. Expect to see the sidebar being collapsed.
5. You may wish to repeat the steps above on other pages.

### Steps to test dashboard
1. Sign into local instance of this branch and go to the `^/dashboard` page.
2. Expect to see the **Internal Release** and **PASS1A 6-Month** button being active by default at the upper-right corner.
3. Click on the **PASS1B 6-Month** button and expect to see the UIs (e.g. various metrics, sample count plot/table) being updated on the dashboard.
4. Click on the **Samples** dropdown menu above the plot and select **Tissue by count**. Expect to see the plot being re-rendered.
5. Click on the **Sort** dropdown menu above the table and select **Tissue name ascending**. Expect to see the table being sorted by tissue name in alphabetical order.

### CODE REVIEW

**Review by ysyskim4 — COMMENTED** [review]
@jimmyzhen This is great work! While I am reviewing the Dashboard page, i have one question. On the 'overview' panel, what does 'Sort: default' mean?

**Comment by jimmyzhen** [comment]
@ysyskim4 Thanks for reviewing the PR. The _default_ sort for the table is by tissue code (e.g. T30). Any suggestion on making it more intuitive will be greatly appreciated!

**Comment by ysyskim4** [comment]
@jimmyzhen thanks for the answer! then just want to suggest one thing for the next version - would it be too much work to add tissue code by adding one more column or by adding tissue code to the tissue name like `T40 Adrenal Powder` instead of `Adrenal Powder` ?

**Review by ysyskim4 — APPROVED** [review]
Great work!

**Comment by jimmyzhen** [comment]
@ysyskim4 Thanks for the suggestion. I can prepend the tissue codes to the tissue names in this version.

**Comment by jimmyzhen** [comment]
@ysyskim4 @cteng585 @kilodalton I have merged the latest version of the `dev` branch into this PR and resolved all the conflicts, along with couple of addition changes:
1. Prepending tissue codes to tissue names in the sample count table as Young recommended.
2. Making the Dashboard the entry page upon authentication.
3. Added messages to clarify that PASS1A-06 and PASS1B-06 phenotypic data consists of 18-month data.

Please review/test again if possible. Thanks!

**Review by cteng585 — APPROVED** [review]
Everything looks good and functions as expected on the dashboard.

Some behavior I noticed (not sure if this is urgent to correct in this PR):
1. Selecting a sorting type in the dashboard (e.g. Assay by Name) will stay preserved even if the user navigates to another part of the data hub
2. Trying to enter a gene name in the "Meta analysis of Public Data" part of the data hub using the "Enter" key clears the entry field. You have to click on the magnifying glass with your mouse right now to have it function correctly.

A suggestion:
Maybe clicking the tissue number or assay number at the top of the dash board applies that sorting method (by name) in the bar graph? I just get this feeling that they should be clickable, but I'm not sure about this.

**Comment by jimmyzhen** [comment]
@cteng585, thank you for taking the time out to review the PR. Your comments and suggestion are greatly appreciated.

### My thoughts on your comment
> Selecting a sorting type in the dashboard (e.g. Assay by Name) will stay preserved even if the user navigates to another part of the data hub.

Persisting the states of sorting on the dashboard (as well as the _release_ and _phase_ filters) is intentional in the attempt to provide convenience to users who return to the dashboard upon looking up other relevant data/analysis on the portal.

> Trying to enter a gene name in the "Meta analysis of Public Data" part of the data hub using the "Enter" key clears the entry field. You have to click on the magnifying glass with your mouse right now to have it function correctly.

Although this behavior is somewhat outside of this PR's scope, I agree that the UX can be improved, especially when the human meta analysis feature has not been fully implemented. My goal is to revisit the analyses with David Amar and make them available on the data hub portal going forward.

> Maybe clicking the tissue number or assay number at the top of the dash board applies that sorting method (by name) in the bar graph? I just get this feeling that they should be clickable, but I'm not sure about this.

This is actually an interesting user observation, since the _highlighted_ metrics are non-interactive. Is it the borders that make them look like buttons, or their placement on the page?

**Comment by cteng585** [comment]
For me, I think it's the borders that make me feel like they should be clickable.

**Comment by jimmyzhen** [comment]
It is possible that the drop shadow makes it looking like a button. I will fiddle with it and see whether something different can be attempted.

Nonetheless, this doesn't sound like a showstopper for the PR to be moved forward.

**Pull request merged**
