### PR TITLE
Connects to #224. Definition of timewise vs training DE in PASS1B data.

### PR DESCRIPTION
**Pull request by jimmyzhen**
### Key Changes:

* Installed react-tooltip dependency to streamline the tooltip implementation and keep it consistent.
* Added hover tooltips to the **Timewise** and **Training** tabs of the result tables on the DEA search page.
* Added hover tooltips to the **timewise** and **training** keyword in the page summary in the Gene-centric view.
* Replaced old tooltip implementation with react-tooltip in the headers of the search result tables in the Gene-centric View and on the DEA search page.
* Minor housekeeping work, such as removing unused CSS and code.

### CODE REVIEW

**Comment by jyu-sm** [comment]
The tooltip for the "Training" tab is "Select differential analytes", is that intentional?

**Comment by jyu-sm** [comment]
In Gene Centric View, if I typed in "brd2" in lower case, I got the error: No valid query given, make sure the query type is correct. Please modify the gene symbol and try again. There is no options to choose the query types on that page. BTW, I logged in as an authorized user. The url is http://dev.motrpac-data.org/gene-centric

**Comment by jimmyzhen** [comment]
> The tooltip for the "Training" tab is "Select differential analytes", is that intentional?

I was given this slide as a reference:
image

**Comment by jimmyzhen** [comment]
> "max abundance over the training periods".

For timewise or training DEA?

**Comment by jyu-sm** [comment]
Training tab

**Review by cteng585 — APPROVED** [review]
Looks good to me. Agreed with Jay on the clarity of the tool tips, but it looks like the most recent commits have addressed this.

**Comment by jimmyzhen** [comment]
Thanks to @biodavidjm, I have updated the tooltip text for the Timewise and Training tabs.

**Pull request merged**
