### PR TITLE
Connects to #95. Node.js, CRA, Auth0, and Storybook version upgrades.

### PR DESCRIPTION
**Pull request by jimmyzhen**
### Technical Notes

**Node.js** `v14.15.4` is required to be running in your local environment when reviewing/testing this PR.

### Key Changes

1. Updated **Circle CI** config to use `node:14.15.4-browsers` docker image.
2. Upgraded **react-scripts** and **react** to latest versions to address vulnerabilities.
3. Bumped versions of **Auth0** and **Storybook** dependencies, along with others.
4. Updated code to comply with **Eslint** rules, while added other **Eslint** rules to temporarily suppress "failed to compile" issues upon upgrading CRA.
5. Updated unit test assertions due to failing tests as a result of version upgrades of node, react, and jest.

### Steps to test

1. Upgrade **Node.js** to `v14.15.4` or use `nvm` to install this version.
2. Clone this PR branch and run the app using `yarn inspect-branch`.
3. Run `yarn audit` in the app's root directory and expect to see the `0 vulnerabilities found` message.
4. Run `yarn test` in the app's root directory and expect to see all tests to pass.
5. Sign in through Auth0 and expect to be able to login successfully.

### CODE REVIEW

**Review by cteng585 — CHANGES_REQUESTED** [review]
Most things look good - 

yarn audit output:
Screen Shot 2021-02-12 at 12 49 53 PM

yarn test output:
Screen Shot 2021-02-12 at 12 51 29 PM

However, although I can log in with Auth0, I am directed to an empty landing page. Refreshing the page after logging in yields the expected dashboard: 
Screen Shot 2021-02-12 at 12 58 50 PM

**Comment by jimmyzhen** [comment]
The reported issue appears to have been caused by the following:
https://github.com/ReactTraining/react-router/issues/7415

As a result, I reverted the `history` dependency from `5.0.0` to be pinned at `4.10.1`. Upon running `rm -fr node_modules/` and `yarn install` again, the issue appears to have been resolved.

**Review by cteng585 — APPROVED** [review]
Empty page issue is resolved, all tests passed when running `yarn test`, and no vulnerabilities found when running `yarn audit`. Great work Jimmy!

**Review by ysyskim4 — APPROVED** [review]
Great work!

**Pull request merged**
